version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ecommerce-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Archivo schema.sql opcional, aunque el backend ejecutará las migraciones de Alembic
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:123456@db:5432/ecommerce-db
      - ENVIRONMENT=production
      - PROJECT_NAME=Ecommerce Platform API
      - API_PREFIX=/api/v1
      - API_VERSION=0.1.0
      - JWT_SECRET_KEY=d0a0df56157a832b200ee42ccb5d0048bee8b5f853881f692c0e6d296755fba1
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecommerce_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
